### ISSUE TITLE
globalInstance window.swup is undefined

### ISSUE THREAD

**Issue by piratey7007** [swup/astro#6]
**Description of the issue**
When assigning `globalInstance: true` in the configuration, window.swup returns undefined.

**How to reproduce the issue**

Just start an astro project with the CLI, install swup with the CLI, and assign globalInstance to true in the config.

**Context and environment**

Happens in Firefox and Chrome, haven't checked others.
@swup/astro version is 1.0.2.

```javascript
// astro.config.mjs
import { defineConfig } from "astro/config";
import swup from "@swup/astro";

export default defineConfig({
  integrations: [
    swup({
      globalInstance: true,
    }),
  ],
});
```

```javascript
// script anywhere in the app
console.log(window.swup) // returns undefined
```

**Before creating this issue...**

- [X] Have you provided all helpful information available?
- [X] Have you checked closed issues for similar/related problems?
- [X] Have you considered creating a demo so we can help you better?

**Comment by daun** [comment]
Hi @piratey7007!

The issue here is that swup doesn't initialize immediately. It waits for the browser to become idle before importing and running swup. You can listen for the `enable` event to run your script once swup is enabled:

```html
<script>
  console.log('swup not yet enabled', window.swup);
  document.addEventListener('swup:enable', () => {
    console.log('swup enabled', window.swup);
  });
</script>
```

I'll create an issue to mention this clearly in the readme. I'll close this as I just tested the above solution, but feel free to reopen or get in touch if you're still seeing it!

**Comment by piratey7007** [comment]
Thanks for clearing things up @daun. Apologies for the confusion. I'm a bit new to swup, but tried my best to figure it out, and thought adding a `setTimeout` of a couple seconds would be fine, but I forgot completely about the deferred nature of swup.

In any case, it all works now, so thanks.
